-- Tabla Clientes
CREATE TABLE Clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    email VARCHAR2(100),
    telefono VARCHAR2(20)
);

-- Tabla Mesas
CREATE TABLE Mesas (
    mesa_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_mesa NUMBER NOT NULL,
    capacidad NUMBER NOT NULL,
    ubicacion VARCHAR2(100)
);

-- Tabla Empleados
CREATE TABLE Empleados (
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    cargo VARCHAR2(50) NOT NULL
);

-- Tabla Reservas
CREATE TABLE Reservas (
    reserva_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    mesa_id NUMBER NOT NULL,
    empleado_id NUMBER NOT NULL,
    fecha_reserva DATE NOT NULL,
    hora_reserva VARCHAR2(5) NOT NULL,
    numero_personas NUMBER NOT NULL,
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (cliente_id) REFERENCES Clientes(cliente_id),
    CONSTRAINT fk_reserva_mesa FOREIGN KEY (mesa_id) REFERENCES Mesas(mesa_id),
    CONSTRAINT fk_reserva_empleado FOREIGN KEY (empleado_id) REFERENCES Empleados(empleado_id)
);

-- Tabla Menús
CREATE TABLE Menus (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_plato VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(7,2) NOT NULL
);

-- Tabla Pedidos
CREATE TABLE Pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id NUMBER NOT NULL,
    menu_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    CONSTRAINT fk_pedido_reserva FOREIGN KEY (reserva_id) REFERENCES Reservas(reserva_id),
    CONSTRAINT fk_pedido_menu FOREIGN KEY (menu_id) REFERENCES Menus(menu_id)
);

-- Índices opcionales para mejorar el rendimiento
CREATE INDEX idx_reservas_cliente ON Reservas(cliente_id);
CREATE INDEX idx_reservas_mesa ON Reservas(mesa_id);
CREATE INDEX idx_pedidos_reserva ON Pedidos(reserva_id);
CREATE INDEX idx_pedidos_menu ON Pedidos(menu_id);