-- Tabla Clientes
CREATE TABLE Clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    email VARCHAR2(100),
    telefono VARCHAR2(20)
);

-- Tabla Mesas
CREATE TABLE Mesas (
    mesa_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_mesa NUMBER NOT NULL,
    capacidad NUMBER NOT NULL,
    ubicacion VARCHAR2(100)
);

-- Tabla Reservas
-- Tabla Reservas actualizada
CREATE TABLE Reservas (
    reserva_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER REFERENCES Clientes(cliente_id),
    mesa_id NUMBER REFERENCES Mesas(mesa_id),
    empleado_id NUMBER REFERENCES Empleados(empleado_id),
    fecha_reserva DATE NOT NULL,
    hora_reserva VARCHAR2(5) NOT NULL,
    numero_personas NUMBER NOT NULL
);


-- Tabla Empleados
CREATE TABLE Empleados (
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    cargo VARCHAR2(50) NOT NULL
);

-- Tabla Menús
CREATE TABLE Menus (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_plato VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(5,2) NOT NULL
);

-- Tabla Pedidos
CREATE TABLE Pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id NUMBER REFERENCES Reservas(reserva_id),
    menu_id NUMBER REFERENCES Menus(menu_id),
    cantidad NUMBER NOT NULL
);

CREATE TABLE Turnos (
    turno_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id NUMBER REFERENCES Empleados(empleado_id),
    fecha DATE NOT NULL,
    hora_inicio VARCHAR2(5) NOT NULL,
    hora_fin VARCHAR2(5) NOT NULL
);

ALTER TABLE Pedidos
ADD empleado_id NUMBER REFERENCES Empleados(empleado_id);